version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/production/Dockerfile
    image: qiaoqian-frontend
    container_name: qiaoqian-frontend
    ports:
      - "80:80"
